### ISSUE TITLE
名人堂报错

### ISSUE THREAD

**Issue by moeskia** [96dl/Tieba-Cloud-Sign-Plugins#5]
TiebaCloudSigner - 提示信息

百度贴吧云签到 V4.92 (PHP 7.2.20) 在工作时发生致命的异常 @ 2020-03-04 15:45:41
消息：#10000 - MySQL 语句执行错误：
语句：INSERT INTO `gzgkogsf`.`tc_ver4_rank_list` (`fid`,`nid`,`name`,`tieba`,`date`) VALUES ('339','2257275437','江户川柯南😇','柯南',1583307941)
错误：#1366 - Incorrect string value: '\xF0\x9F\x98\x87' for column 'name' at row 1
文件 | 行 | 代码
-- | -- | --
/home/ftp/g/gzgkogsf/wwwroot/lib/class.mysqli.php | 120 | [抛出异常]
/home/ftp/g/gzgkogsf/wwwroot/plugins/ver4_rank/cron/daily.php | 24 | query
/home/ftp/g/gzgkogsf/wwwroot/lib/class.cron.php | 190 | include_once
/home/ftp/g/gzgkogsf/wwwroot/setting.php | 449 | run

已经开了小标签

**Comment by n0099** [comment]
所有表和字段编码/排序规则改成utf8mb4（mysql8+用utf8mb4_0900_ai_ci，8-用utf8mb4_unicode_ci）后才能存储emoji字符

**Comment by moeskia** [comment]
切换之后他就报非法字节集混用,然后改了回来,我就想到用str_replace()把这个emoji替换为空,毕竟只有一个emoji,但是我把这个写到$uinfo那里后不报错了,但是rank_list一个也没有了,望大佬解惑

**Comment by moeskia** [comment]
还有,这个str_replace我拿到本地测试过,的确把json里面的这个emoji替换掉了,但是写到daily里面之后rank_list一个也没有了,报编码错误的时候直到名称带emoji的可以被添加进去

**Comment by moeskia** [comment]
计划任务也可以成功执行

**Comment by moeskia** [comment]
原来还有一个日期判断,修改了一下,成功执行了,改回来,完事了,打扰了
